// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "enterprise/models/addresses-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // eAddresses
  //

  const char access::object_traits_impl< ::eAddresses, id_pgsql >::
  persist_statement_name[] = "persist_eAddresses";

  const char access::object_traits_impl< ::eAddresses, id_pgsql >::
  find_statement_name[] = "find_eAddresses";

  const char access::object_traits_impl< ::eAddresses, id_pgsql >::
  update_statement_name[] = "update_eAddresses";

  const char access::object_traits_impl< ::eAddresses, id_pgsql >::
  erase_statement_name[] = "erase_eAddresses";

  const char access::object_traits_impl< ::eAddresses, id_pgsql >::
  query_statement_name[] = "query_eAddresses";

  const char access::object_traits_impl< ::eAddresses, id_pgsql >::
  erase_query_statement_name[] = "erase_query_eAddresses";

  const unsigned int access::object_traits_impl< ::eAddresses, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::text_oid
  };

  const unsigned int access::object_traits_impl< ::eAddresses, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int4_oid
  };

  const unsigned int access::object_traits_impl< ::eAddresses, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::text_oid,
    pgsql::int4_oid
  };

  struct access::object_traits_impl< ::eAddresses, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::eAddresses, id_pgsql >::id_type
  access::object_traits_impl< ::eAddresses, id_pgsql >::
  id (const id_image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::eAddresses, id_pgsql >::id_type
  access::object_traits_impl< ::eAddresses, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::eAddresses, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id
    //
    t[0UL] = 0;

    // script_id
    //
    if (t[1UL])
    {
      i.script_id_value.capacity (i.script_id_size);
      grew = true;
    }

    // address
    //
    if (t[2UL])
    {
      i.address_value.capacity (i.address_size);
      grew = true;
    }

    // source_type
    //
    if (t[3UL])
    {
      i.source_type_value.capacity (i.source_type_size);
      grew = true;
    }

    // hex
    //
    if (t[4UL])
    {
      i.hex_value.capacity (i.hex_size);
      grew = true;
    }

    // version
    //
    t[5UL] = 0;

    // length
    //
    t[6UL] = 0;

    // program
    //
    if (t[7UL])
    {
      i.program_value.capacity (i.program_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::eAddresses, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // id
    //
    if (sk != statement_insert && sk != statement_update)
    {
      b[n].type = pgsql::bind::integer;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // script_id
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.script_id_value.data ();
    b[n].capacity = i.script_id_value.capacity ();
    b[n].size = &i.script_id_size;
    b[n].is_null = &i.script_id_null;
    n++;

    // address
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.address_value.data ();
    b[n].capacity = i.address_value.capacity ();
    b[n].size = &i.address_size;
    b[n].is_null = &i.address_null;
    n++;

    // source_type
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.source_type_value.data ();
    b[n].capacity = i.source_type_value.capacity ();
    b[n].size = &i.source_type_size;
    b[n].is_null = &i.source_type_null;
    n++;

    // hex
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.hex_value.data ();
    b[n].capacity = i.hex_value.capacity ();
    b[n].size = &i.hex_size;
    b[n].is_null = &i.hex_null;
    n++;

    // version
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.version_value;
    b[n].is_null = &i.version_null;
    n++;

    // length
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.length_value;
    b[n].is_null = &i.length_null;
    n++;

    // program
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.program_value.data ();
    b[n].capacity = i.program_value.capacity ();
    b[n].size = &i.program_size;
    b[n].is_null = &i.program_null;
    n++;
  }

  void access::object_traits_impl< ::eAddresses, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::eAddresses, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // script_id
    //
    {
      ::std::string const& v =
        o.script_id;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.script_id_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.script_id_value,
        size,
        is_null,
        v);
      i.script_id_null = is_null;
      i.script_id_size = size;
      grew = grew || (cap != i.script_id_value.capacity ());
    }

    // address
    //
    {
      ::std::string const& v =
        o.address;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.address_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.address_value,
        size,
        is_null,
        v);
      i.address_null = is_null;
      i.address_size = size;
      grew = grew || (cap != i.address_value.capacity ());
    }

    // source_type
    //
    {
      ::std::string const& v =
        o.source_type;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.source_type_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.source_type_value,
        size,
        is_null,
        v);
      i.source_type_null = is_null;
      i.source_type_size = size;
      grew = grew || (cap != i.source_type_value.capacity ());
    }

    // hex
    //
    {
      ::std::string const& v =
        o.hex;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.hex_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.hex_value,
        size,
        is_null,
        v);
      i.hex_null = is_null;
      i.hex_size = size;
      grew = grew || (cap != i.hex_value.capacity ());
    }

    // version
    //
    {
      unsigned int const& v =
        o.version;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.version_value, is_null, v);
      i.version_null = is_null;
    }

    // length
    //
    {
      unsigned int const& v =
        o.length;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.length_value, is_null, v);
      i.length_null = is_null;
    }

    // program
    //
    {
      ::std::string const& v =
        o.program;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.program_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.program_value,
        size,
        is_null,
        v);
      i.program_null = is_null;
      i.program_size = size;
      grew = grew || (cap != i.program_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::eAddresses, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id
    //
    {
      unsigned int& v =
        o.id;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // script_id
    //
    {
      ::std::string& v =
        o.script_id;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.script_id_value,
        i.script_id_size,
        i.script_id_null);
    }

    // address
    //
    {
      ::std::string& v =
        o.address;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.address_value,
        i.address_size,
        i.address_null);
    }

    // source_type
    //
    {
      ::std::string& v =
        o.source_type;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.source_type_value,
        i.source_type_size,
        i.source_type_null);
    }

    // hex
    //
    {
      ::std::string& v =
        o.hex;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.hex_value,
        i.hex_size,
        i.hex_null);
    }

    // version
    //
    {
      unsigned int& v =
        o.version;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i.version_value,
        i.version_null);
    }

    // length
    //
    {
      unsigned int& v =
        o.length;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i.length_value,
        i.length_null);
    }

    // program
    //
    {
      ::std::string& v =
        o.program;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.program_value,
        i.program_size,
        i.program_null);
    }
  }

  void access::object_traits_impl< ::eAddresses, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::eAddresses, id_pgsql >::persist_statement[] =
  "INSERT INTO \"bitcoin\".\"eAddresses\" "
  "(\"id\", "
  "\"script_id\", "
  "\"address\", "
  "\"source_type\", "
  "\"hex\", "
  "\"version\", "
  "\"length\", "
  "\"program\") "
  "VALUES "
  "(DEFAULT, $1, $2, $3, $4, $5, $6, $7) "
  "RETURNING \"id\"";

  const char access::object_traits_impl< ::eAddresses, id_pgsql >::find_statement[] =
  "SELECT "
  "\"bitcoin\".\"eAddresses\".\"id\", "
  "\"bitcoin\".\"eAddresses\".\"script_id\", "
  "\"bitcoin\".\"eAddresses\".\"address\", "
  "\"bitcoin\".\"eAddresses\".\"source_type\", "
  "\"bitcoin\".\"eAddresses\".\"hex\", "
  "\"bitcoin\".\"eAddresses\".\"version\", "
  "\"bitcoin\".\"eAddresses\".\"length\", "
  "\"bitcoin\".\"eAddresses\".\"program\" "
  "FROM \"bitcoin\".\"eAddresses\" "
  "WHERE \"bitcoin\".\"eAddresses\".\"id\"=$1";

  const char access::object_traits_impl< ::eAddresses, id_pgsql >::update_statement[] =
  "UPDATE \"bitcoin\".\"eAddresses\" "
  "SET "
  "\"script_id\"=$1, "
  "\"address\"=$2, "
  "\"source_type\"=$3, "
  "\"hex\"=$4, "
  "\"version\"=$5, "
  "\"length\"=$6, "
  "\"program\"=$7 "
  "WHERE \"id\"=$8";

  const char access::object_traits_impl< ::eAddresses, id_pgsql >::erase_statement[] =
  "DELETE FROM \"bitcoin\".\"eAddresses\" "
  "WHERE \"id\"=$1";

  const char access::object_traits_impl< ::eAddresses, id_pgsql >::query_statement[] =
  "SELECT "
  "\"bitcoin\".\"eAddresses\".\"id\", "
  "\"bitcoin\".\"eAddresses\".\"script_id\", "
  "\"bitcoin\".\"eAddresses\".\"address\", "
  "\"bitcoin\".\"eAddresses\".\"source_type\", "
  "\"bitcoin\".\"eAddresses\".\"hex\", "
  "\"bitcoin\".\"eAddresses\".\"version\", "
  "\"bitcoin\".\"eAddresses\".\"length\", "
  "\"bitcoin\".\"eAddresses\".\"program\" "
  "FROM \"bitcoin\".\"eAddresses\"";

  const char access::object_traits_impl< ::eAddresses, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"bitcoin\".\"eAddresses\"";

  const char access::object_traits_impl< ::eAddresses, id_pgsql >::table_name[] =
  "\"bitcoin\".\"eAddresses\"";

  void access::object_traits_impl< ::eAddresses, id_pgsql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::eAddresses, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::eAddresses, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    ODB_POTENTIALLY_UNUSED (db);

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::eAddresses, id_pgsql >::pointer_type
  access::object_traits_impl< ::eAddresses, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::eAddresses, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::eAddresses, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::eAddresses, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::eAddresses, id_pgsql >::object_type >
  access::object_traits_impl< ::eAddresses, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::eAddresses, id_pgsql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
