/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "bitcoin"."eAddresses" CASCADE;

DROP TABLE IF EXISTS "schema_version";

CREATE TABLE "bitcoin"."eAddresses" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "script_id" TEXT NOT NULL,
  "address" TEXT NOT NULL,
  "source_type" TEXT NOT NULL,
  "hex" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "length" INTEGER NOT NULL,
  "program" TEXT NOT NULL);

CREATE TABLE "schema_version" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "version" BIGINT NOT NULL,
  "migration" BOOLEAN NOT NULL);

INSERT INTO "schema_version" (
  "name", "version", "migration")
  VALUES ('', 1, FALSE);

