// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef BLOCKS_ODB_HXX
#define BLOCKS_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "enterprise/models/blocks.h"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // eBlocks
  //
  template <>
  struct class_traits< ::eBlocks >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::eBlocks >
  {
    public:
    typedef ::eBlocks object_type;
    typedef ::eBlocks* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // eBlocks
  //
  template <typename A>
  struct query_columns< ::eBlocks, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    id_type_;

    static const id_type_ id;

    // hash
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    hash_type_;

    static const hash_type_ hash;

    // merkle_root
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    merkle_root_type_;

    static const merkle_root_type_ merkle_root;

    // time
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    time_type_;

    static const time_type_ time;

    // median_time
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    median_time_type_;

    static const median_time_type_ median_time;

    // height
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    height_type_;

    static const height_type_ height;

    // subsidy
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    subsidy_type_;

    static const subsidy_type_ subsidy;

    // transactions_count
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    transactions_count_type_;

    static const transactions_count_type_ transactions_count;

    // version
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint32_t,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    version_type_;

    static const version_type_ version;

    // status
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint32_t,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    status_type_;

    static const status_type_ status;

    // bits
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint32_t,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    bits_type_;

    static const bits_type_ bits;

    // nonce
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    nonce_type_;

    static const nonce_type_ nonce;

    // difficulty
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        double,
        pgsql::id_double >::query_type,
      pgsql::id_double >
    difficulty_type_;

    static const difficulty_type_ difficulty;

    // chain_work
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    chain_work_type_;

    static const chain_work_type_ chain_work;

    // fee_data
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    fee_data_type_;

    static const fee_data_type_ fee_data;

    // output_data
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    output_data_type_;

    static const output_data_type_ output_data;

    // input_data
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    input_data_type_;

    static const input_data_type_ input_data;

    // segwit_spend_count
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    segwit_spend_count_type_;

    static const segwit_spend_count_type_ segwit_spend_count;

    // outputs_count
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    outputs_count_type_;

    static const outputs_count_type_ outputs_count;

    // inputs_count
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    inputs_count_type_;

    static const inputs_count_type_ inputs_count;

    // total_output_value
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    total_output_value_type_;

    static const total_output_value_type_ total_output_value;

    // total_fees
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    total_fees_type_;

    static const total_fees_type_ total_fees;

    // total_size
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    total_size_type_;

    static const total_size_type_ total_size;

    // total_vsize
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    total_vsize_type_;

    static const total_vsize_type_ total_vsize;

    // total_weight
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    total_weight_type_;

    static const total_weight_type_ total_weight;
  };

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::id_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::hash_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  hash (A::table_name, "\"hash\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::merkle_root_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  merkle_root (A::table_name, "\"merkle_root\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::time_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  time (A::table_name, "\"time\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::median_time_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  median_time (A::table_name, "\"median_time\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::height_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  height (A::table_name, "\"height\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::subsidy_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  subsidy (A::table_name, "\"subsidy\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::transactions_count_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  transactions_count (A::table_name, "\"transactions_count\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::version_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  version (A::table_name, "\"version\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::status_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  status (A::table_name, "\"status\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::bits_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  bits (A::table_name, "\"bits\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::nonce_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  nonce (A::table_name, "\"nonce\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::difficulty_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  difficulty (A::table_name, "\"difficulty\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::chain_work_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  chain_work (A::table_name, "\"chain_work\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::fee_data_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  fee_data (A::table_name, "\"fee_data\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::output_data_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  output_data (A::table_name, "\"output_data\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::input_data_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  input_data (A::table_name, "\"input_data\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::segwit_spend_count_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  segwit_spend_count (A::table_name, "\"segwit_spend_count\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::outputs_count_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  outputs_count (A::table_name, "\"outputs_count\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::inputs_count_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  inputs_count (A::table_name, "\"inputs_count\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::total_output_value_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  total_output_value (A::table_name, "\"total_output_value\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::total_fees_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  total_fees (A::table_name, "\"total_fees\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::total_size_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  total_size (A::table_name, "\"total_size\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::total_vsize_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  total_vsize (A::table_name, "\"total_vsize\"", 0);

  template <typename A>
  const typename query_columns< ::eBlocks, id_pgsql, A >::total_weight_type_
  query_columns< ::eBlocks, id_pgsql, A >::
  total_weight (A::table_name, "\"total_weight\"", 0);

  template <typename A>
  struct pointer_query_columns< ::eBlocks, id_pgsql, A >:
    query_columns< ::eBlocks, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::eBlocks, id_pgsql >:
    public access::object_traits< ::eBlocks >
  {
    public:
    struct id_image_type
    {
      int id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      int id_value;
      bool id_null;

      // hash
      //
      details::buffer hash_value;
      std::size_t hash_size;
      bool hash_null;

      // merkle_root
      //
      details::buffer merkle_root_value;
      std::size_t merkle_root_size;
      bool merkle_root_null;

      // time
      //
      long long time_value;
      bool time_null;

      // median_time
      //
      long long median_time_value;
      bool median_time_null;

      // height
      //
      long long height_value;
      bool height_null;

      // subsidy
      //
      long long subsidy_value;
      bool subsidy_null;

      // transactions_count
      //
      int transactions_count_value;
      bool transactions_count_null;

      // version
      //
      int version_value;
      bool version_null;

      // status
      //
      int status_value;
      bool status_null;

      // bits
      //
      int bits_value;
      bool bits_null;

      // nonce
      //
      long long nonce_value;
      bool nonce_null;

      // difficulty
      //
      double difficulty_value;
      bool difficulty_null;

      // chain_work
      //
      details::buffer chain_work_value;
      std::size_t chain_work_size;
      bool chain_work_null;

      // fee_data
      //
      details::buffer fee_data_value;
      std::size_t fee_data_size;
      bool fee_data_null;

      // output_data
      //
      details::buffer output_data_value;
      std::size_t output_data_size;
      bool output_data_null;

      // input_data
      //
      details::buffer input_data_value;
      std::size_t input_data_size;
      bool input_data_null;

      // segwit_spend_count
      //
      long long segwit_spend_count_value;
      bool segwit_spend_count_null;

      // outputs_count
      //
      long long outputs_count_value;
      bool outputs_count_null;

      // inputs_count
      //
      long long inputs_count_value;
      bool inputs_count_null;

      // total_output_value
      //
      long long total_output_value_value;
      bool total_output_value_null;

      // total_fees
      //
      long long total_fees_value;
      bool total_fees_null;

      // total_size
      //
      long long total_size_value;
      bool total_size_null;

      // total_vsize
      //
      long long total_vsize_value;
      bool total_vsize_null;

      // total_weight
      //
      long long total_weight_value;
      bool total_weight_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 25UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::eBlocks, id_common >:
    public access::object_traits_impl< ::eBlocks, id_pgsql >
  {
  };

  // eBlocks
  //
}

#include "enterprise/models/blocks-odb.ixx"

#include <odb/post.hxx>

#endif // BLOCKS_ODB_HXX
