/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "bitcoin"."eBlocks" CASCADE;

DROP TABLE IF EXISTS "schema_version";

CREATE TABLE "bitcoin"."eBlocks" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "hash" TEXT NOT NULL,
  "merkle_root" TEXT NOT NULL,
  "time" BIGINT NOT NULL,
  "height" BIGINT NOT NULL,
  "transactions_count" INTEGER NOT NULL,
  "version" INTEGER NOT NULL,
  "status" INTEGER NOT NULL,
  "bits" INTEGER NOT NULL,
  "nonce" BIGINT NOT NULL);

CREATE TABLE "schema_version" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "version" BIGINT NOT NULL,
  "migration" BOOLEAN NOT NULL);

INSERT INTO "schema_version" (
  "name", "version", "migration")
  VALUES ('', 1, FALSE);

