/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "bitcoin"."eBlocks" CASCADE;

DROP TABLE IF EXISTS "schema_version";

CREATE TABLE "bitcoin"."eBlocks" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "hash" TEXT NOT NULL,
  "merkle_root" TEXT NOT NULL,
  "time" BIGINT NOT NULL,
  "median_time" BIGINT NOT NULL,
  "height" BIGINT NOT NULL,
  "subsidy" BIGINT NOT NULL,
  "transactions_count" INTEGER NOT NULL,
  "version" INTEGER NOT NULL,
  "status" INTEGER NOT NULL,
  "bits" INTEGER NOT NULL,
  "nonce" BIGINT NOT NULL,
  "difficulty" DOUBLE PRECISION NOT NULL,
  "chain_work" TEXT NOT NULL,
  "fee_data" TEXT NOT NULL,
  "segwit_spend_count" BIGINT NOT NULL,
  "outputs_count" BIGINT NOT NULL,
  "inputs_count" BIGINT NOT NULL,
  "total_output_value" BIGINT NOT NULL,
  "total_fees" BIGINT NOT NULL,
  "total_size" BIGINT NOT NULL,
  "total_vsize" BIGINT NOT NULL,
  "total_weight" BIGINT NOT NULL);

CREATE TABLE "schema_version" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "version" BIGINT NOT NULL,
  "migration" BOOLEAN NOT NULL);

INSERT INTO "schema_version" (
  "name", "version", "migration")
  VALUES ('', 1, FALSE);

