// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef INPUTS_ODB_HXX
#define INPUTS_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "enterprise/models/inputs.h"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // eInputs
  //
  template <>
  struct class_traits< ::eInputs >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::eInputs >
  {
    public:
    typedef ::eInputs object_type;
    typedef ::eInputs* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // eInputs
  //
  template <typename A>
  struct query_columns< ::eInputs, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    id_type_;

    static const id_type_ id;

    // output_transaction_hash
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    output_transaction_hash_type_;

    static const output_transaction_hash_type_ output_transaction_hash;

    // output_vector
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    output_vector_type_;

    static const output_vector_type_ output_vector;

    // block_hash
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    block_hash_type_;

    static const block_hash_type_ block_hash;

    // transaction_block_index
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    transaction_block_index_type_;

    static const transaction_block_index_type_ transaction_block_index;

    // transaction_hash
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    transaction_hash_type_;

    static const transaction_hash_type_ transaction_hash;

    // vector
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    vector_type_;

    static const vector_type_ vector;

    // unlocking_script_id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    unlocking_script_id_type_;

    static const unlocking_script_id_type_ unlocking_script_id;

    // sequence
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint32_t,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    sequence_type_;

    static const sequence_type_ sequence;
  };

  template <typename A>
  const typename query_columns< ::eInputs, id_pgsql, A >::id_type_
  query_columns< ::eInputs, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::eInputs, id_pgsql, A >::output_transaction_hash_type_
  query_columns< ::eInputs, id_pgsql, A >::
  output_transaction_hash (A::table_name, "\"output_transaction_hash\"", 0);

  template <typename A>
  const typename query_columns< ::eInputs, id_pgsql, A >::output_vector_type_
  query_columns< ::eInputs, id_pgsql, A >::
  output_vector (A::table_name, "\"output_vector\"", 0);

  template <typename A>
  const typename query_columns< ::eInputs, id_pgsql, A >::block_hash_type_
  query_columns< ::eInputs, id_pgsql, A >::
  block_hash (A::table_name, "\"block_hash\"", 0);

  template <typename A>
  const typename query_columns< ::eInputs, id_pgsql, A >::transaction_block_index_type_
  query_columns< ::eInputs, id_pgsql, A >::
  transaction_block_index (A::table_name, "\"transaction_block_index\"", 0);

  template <typename A>
  const typename query_columns< ::eInputs, id_pgsql, A >::transaction_hash_type_
  query_columns< ::eInputs, id_pgsql, A >::
  transaction_hash (A::table_name, "\"transaction_hash\"", 0);

  template <typename A>
  const typename query_columns< ::eInputs, id_pgsql, A >::vector_type_
  query_columns< ::eInputs, id_pgsql, A >::
  vector (A::table_name, "\"vector\"", 0);

  template <typename A>
  const typename query_columns< ::eInputs, id_pgsql, A >::unlocking_script_id_type_
  query_columns< ::eInputs, id_pgsql, A >::
  unlocking_script_id (A::table_name, "\"unlocking_script_id\"", 0);

  template <typename A>
  const typename query_columns< ::eInputs, id_pgsql, A >::sequence_type_
  query_columns< ::eInputs, id_pgsql, A >::
  sequence (A::table_name, "\"sequence\"", 0);

  template <typename A>
  struct pointer_query_columns< ::eInputs, id_pgsql, A >:
    query_columns< ::eInputs, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::eInputs, id_pgsql >:
    public access::object_traits< ::eInputs >
  {
    public:
    struct id_image_type
    {
      int id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      int id_value;
      bool id_null;

      // output_transaction_hash
      //
      details::buffer output_transaction_hash_value;
      std::size_t output_transaction_hash_size;
      bool output_transaction_hash_null;

      // output_vector
      //
      int output_vector_value;
      bool output_vector_null;

      // block_hash
      //
      details::buffer block_hash_value;
      std::size_t block_hash_size;
      bool block_hash_null;

      // transaction_block_index
      //
      int transaction_block_index_value;
      bool transaction_block_index_null;

      // transaction_hash
      //
      details::buffer transaction_hash_value;
      std::size_t transaction_hash_size;
      bool transaction_hash_null;

      // vector
      //
      int vector_value;
      bool vector_null;

      // unlocking_script_id
      //
      details::buffer unlocking_script_id_value;
      std::size_t unlocking_script_id_size;
      bool unlocking_script_id_null;

      // sequence
      //
      int sequence_value;
      bool sequence_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 9UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::eInputs, id_common >:
    public access::object_traits_impl< ::eInputs, id_pgsql >
  {
  };

  // eInputs
  //
}

#include "enterprise/models/inputs-odb.ixx"

#include <odb/post.hxx>

#endif // INPUTS_ODB_HXX
