/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "bitcoin"."eOutputs" CASCADE;

DROP TABLE IF EXISTS "schema_version";

CREATE TABLE "bitcoin"."eOutputs" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "block_hash" TEXT NOT NULL,
  "transaction_block_index" INTEGER NOT NULL,
  "transaction_hash" TEXT NOT NULL,
  "vector" INTEGER NOT NULL,
  "value" BIGINT NOT NULL,
  "locking_script_id" TEXT NOT NULL,
  "required_signatures" INTEGER NOT NULL);

CREATE TABLE "schema_version" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "version" BIGINT NOT NULL,
  "migration" BOOLEAN NOT NULL);

INSERT INTO "schema_version" (
  "name", "version", "migration")
  VALUES ('', 1, FALSE);

