// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "enterprise/models/transactions-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // eTransactions
  //

  const char access::object_traits_impl< ::eTransactions, id_pgsql >::
  persist_statement_name[] = "persist_eTransactions";

  const char access::object_traits_impl< ::eTransactions, id_pgsql >::
  find_statement_name[] = "find_eTransactions";

  const char access::object_traits_impl< ::eTransactions, id_pgsql >::
  update_statement_name[] = "update_eTransactions";

  const char access::object_traits_impl< ::eTransactions, id_pgsql >::
  erase_statement_name[] = "erase_eTransactions";

  const char access::object_traits_impl< ::eTransactions, id_pgsql >::
  query_statement_name[] = "query_eTransactions";

  const char access::object_traits_impl< ::eTransactions, id_pgsql >::
  erase_query_statement_name[] = "erase_query_eTransactions";

  const unsigned int access::object_traits_impl< ::eTransactions, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::bool_oid,
    pgsql::bool_oid,
    pgsql::bool_oid,
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid
  };

  const unsigned int access::object_traits_impl< ::eTransactions, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int4_oid
  };

  const unsigned int access::object_traits_impl< ::eTransactions, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::bool_oid,
    pgsql::bool_oid,
    pgsql::bool_oid,
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::int8_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::float4_oid,
    pgsql::int4_oid
  };

  struct access::object_traits_impl< ::eTransactions, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::eTransactions, id_pgsql >::id_type
  access::object_traits_impl< ::eTransactions, id_pgsql >::
  id (const id_image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::eTransactions, id_pgsql >::id_type
  access::object_traits_impl< ::eTransactions, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::eTransactions, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id
    //
    t[0UL] = 0;

    // block_hash
    //
    if (t[1UL])
    {
      i.block_hash_value.capacity (i.block_hash_size);
      grew = true;
    }

    // index
    //
    t[2UL] = 0;

    // size
    //
    t[3UL] = 0;

    // vsize
    //
    t[4UL] = 0;

    // weight
    //
    t[5UL] = 0;

    // inputs_count
    //
    t[6UL] = 0;

    // outputs_count
    //
    t[7UL] = 0;

    // lock_time
    //
    t[8UL] = 0;

    // version
    //
    t[9UL] = 0;

    // hash
    //
    if (t[10UL])
    {
      i.hash_value.capacity (i.hash_size);
      grew = true;
    }

    // witness_hash
    //
    if (t[11UL])
    {
      i.witness_hash_value.capacity (i.witness_hash_size);
      grew = true;
    }

    // is_coinbase
    //
    t[12UL] = 0;

    // has_witness
    //
    t[13UL] = 0;

    // is_segwit_out_spend
    //
    t[14UL] = 0;

    // total_output_value
    //
    t[15UL] = 0;

    // total_input_value
    //
    t[16UL] = 0;

    // fees
    //
    t[17UL] = 0;

    // fee_per_byte
    //
    t[18UL] = 0;

    // fee_per_vbyte
    //
    t[19UL] = 0;

    // fee_per_weight_unit
    //
    t[20UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::eTransactions, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // id
    //
    if (sk != statement_insert && sk != statement_update)
    {
      b[n].type = pgsql::bind::integer;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // block_hash
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.block_hash_value.data ();
    b[n].capacity = i.block_hash_value.capacity ();
    b[n].size = &i.block_hash_size;
    b[n].is_null = &i.block_hash_null;
    n++;

    // index
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.index_value;
    b[n].is_null = &i.index_null;
    n++;

    // size
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.size_value;
    b[n].is_null = &i.size_null;
    n++;

    // vsize
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.vsize_value;
    b[n].is_null = &i.vsize_null;
    n++;

    // weight
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.weight_value;
    b[n].is_null = &i.weight_null;
    n++;

    // inputs_count
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.inputs_count_value;
    b[n].is_null = &i.inputs_count_null;
    n++;

    // outputs_count
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.outputs_count_value;
    b[n].is_null = &i.outputs_count_null;
    n++;

    // lock_time
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.lock_time_value;
    b[n].is_null = &i.lock_time_null;
    n++;

    // version
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.version_value;
    b[n].is_null = &i.version_null;
    n++;

    // hash
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.hash_value.data ();
    b[n].capacity = i.hash_value.capacity ();
    b[n].size = &i.hash_size;
    b[n].is_null = &i.hash_null;
    n++;

    // witness_hash
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.witness_hash_value.data ();
    b[n].capacity = i.witness_hash_value.capacity ();
    b[n].size = &i.witness_hash_size;
    b[n].is_null = &i.witness_hash_null;
    n++;

    // is_coinbase
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.is_coinbase_value;
    b[n].is_null = &i.is_coinbase_null;
    n++;

    // has_witness
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.has_witness_value;
    b[n].is_null = &i.has_witness_null;
    n++;

    // is_segwit_out_spend
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.is_segwit_out_spend_value;
    b[n].is_null = &i.is_segwit_out_spend_null;
    n++;

    // total_output_value
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.total_output_value_value;
    b[n].is_null = &i.total_output_value_null;
    n++;

    // total_input_value
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.total_input_value_value;
    b[n].is_null = &i.total_input_value_null;
    n++;

    // fees
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.fees_value;
    b[n].is_null = &i.fees_null;
    n++;

    // fee_per_byte
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.fee_per_byte_value;
    b[n].is_null = &i.fee_per_byte_null;
    n++;

    // fee_per_vbyte
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.fee_per_vbyte_value;
    b[n].is_null = &i.fee_per_vbyte_null;
    n++;

    // fee_per_weight_unit
    //
    b[n].type = pgsql::bind::real;
    b[n].buffer = &i.fee_per_weight_unit_value;
    b[n].is_null = &i.fee_per_weight_unit_null;
    n++;
  }

  void access::object_traits_impl< ::eTransactions, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::eTransactions, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // block_hash
    //
    {
      ::std::string const& v =
        o.block_hash;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.block_hash_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.block_hash_value,
        size,
        is_null,
        v);
      i.block_hash_null = is_null;
      i.block_hash_size = size;
      grew = grew || (cap != i.block_hash_value.capacity ());
    }

    // index
    //
    {
      unsigned int const& v =
        o.index;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.index_value, is_null, v);
      i.index_null = is_null;
    }

    // size
    //
    {
      unsigned int const& v =
        o.size;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.size_value, is_null, v);
      i.size_null = is_null;
    }

    // vsize
    //
    {
      unsigned int const& v =
        o.vsize;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.vsize_value, is_null, v);
      i.vsize_null = is_null;
    }

    // weight
    //
    {
      unsigned int const& v =
        o.weight;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.weight_value, is_null, v);
      i.weight_null = is_null;
    }

    // inputs_count
    //
    {
      unsigned int const& v =
        o.inputs_count;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.inputs_count_value, is_null, v);
      i.inputs_count_null = is_null;
    }

    // outputs_count
    //
    {
      unsigned int const& v =
        o.outputs_count;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.outputs_count_value, is_null, v);
      i.outputs_count_null = is_null;
    }

    // lock_time
    //
    {
      ::int32_t const& v =
        o.lock_time;

      bool is_null (false);
      pgsql::value_traits<
          ::int32_t,
          pgsql::id_integer >::set_image (
        i.lock_time_value, is_null, v);
      i.lock_time_null = is_null;
    }

    // version
    //
    {
      ::int32_t const& v =
        o.version;

      bool is_null (false);
      pgsql::value_traits<
          ::int32_t,
          pgsql::id_integer >::set_image (
        i.version_value, is_null, v);
      i.version_null = is_null;
    }

    // hash
    //
    {
      ::std::string const& v =
        o.hash;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.hash_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.hash_value,
        size,
        is_null,
        v);
      i.hash_null = is_null;
      i.hash_size = size;
      grew = grew || (cap != i.hash_value.capacity ());
    }

    // witness_hash
    //
    {
      ::std::string const& v =
        o.witness_hash;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.witness_hash_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.witness_hash_value,
        size,
        is_null,
        v);
      i.witness_hash_null = is_null;
      i.witness_hash_size = size;
      grew = grew || (cap != i.witness_hash_value.capacity ());
    }

    // is_coinbase
    //
    {
      bool const& v =
        o.is_coinbase;

      bool is_null (false);
      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_image (
        i.is_coinbase_value, is_null, v);
      i.is_coinbase_null = is_null;
    }

    // has_witness
    //
    {
      bool const& v =
        o.has_witness;

      bool is_null (false);
      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_image (
        i.has_witness_value, is_null, v);
      i.has_witness_null = is_null;
    }

    // is_segwit_out_spend
    //
    {
      bool const& v =
        o.is_segwit_out_spend;

      bool is_null (false);
      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_image (
        i.is_segwit_out_spend_value, is_null, v);
      i.is_segwit_out_spend_null = is_null;
    }

    // total_output_value
    //
    {
      ::int64_t const& v =
        o.total_output_value;

      bool is_null (false);
      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_image (
        i.total_output_value_value, is_null, v);
      i.total_output_value_null = is_null;
    }

    // total_input_value
    //
    {
      ::int64_t const& v =
        o.total_input_value;

      bool is_null (false);
      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_image (
        i.total_input_value_value, is_null, v);
      i.total_input_value_null = is_null;
    }

    // fees
    //
    {
      ::int64_t const& v =
        o.fees;

      bool is_null (false);
      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_image (
        i.fees_value, is_null, v);
      i.fees_null = is_null;
    }

    // fee_per_byte
    //
    {
      float const& v =
        o.fee_per_byte;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.fee_per_byte_value, is_null, v);
      i.fee_per_byte_null = is_null;
    }

    // fee_per_vbyte
    //
    {
      float const& v =
        o.fee_per_vbyte;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.fee_per_vbyte_value, is_null, v);
      i.fee_per_vbyte_null = is_null;
    }

    // fee_per_weight_unit
    //
    {
      float const& v =
        o.fee_per_weight_unit;

      bool is_null (false);
      pgsql::value_traits<
          float,
          pgsql::id_real >::set_image (
        i.fee_per_weight_unit_value, is_null, v);
      i.fee_per_weight_unit_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::eTransactions, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id
    //
    {
      unsigned int& v =
        o.id;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // block_hash
    //
    {
      ::std::string& v =
        o.block_hash;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.block_hash_value,
        i.block_hash_size,
        i.block_hash_null);
    }

    // index
    //
    {
      unsigned int& v =
        o.index;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i.index_value,
        i.index_null);
    }

    // size
    //
    {
      unsigned int& v =
        o.size;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i.size_value,
        i.size_null);
    }

    // vsize
    //
    {
      unsigned int& v =
        o.vsize;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i.vsize_value,
        i.vsize_null);
    }

    // weight
    //
    {
      unsigned int& v =
        o.weight;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i.weight_value,
        i.weight_null);
    }

    // inputs_count
    //
    {
      unsigned int& v =
        o.inputs_count;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i.inputs_count_value,
        i.inputs_count_null);
    }

    // outputs_count
    //
    {
      unsigned int& v =
        o.outputs_count;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i.outputs_count_value,
        i.outputs_count_null);
    }

    // lock_time
    //
    {
      ::int32_t& v =
        o.lock_time;

      pgsql::value_traits<
          ::int32_t,
          pgsql::id_integer >::set_value (
        v,
        i.lock_time_value,
        i.lock_time_null);
    }

    // version
    //
    {
      ::int32_t& v =
        o.version;

      pgsql::value_traits<
          ::int32_t,
          pgsql::id_integer >::set_value (
        v,
        i.version_value,
        i.version_null);
    }

    // hash
    //
    {
      ::std::string& v =
        o.hash;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.hash_value,
        i.hash_size,
        i.hash_null);
    }

    // witness_hash
    //
    {
      ::std::string& v =
        o.witness_hash;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.witness_hash_value,
        i.witness_hash_size,
        i.witness_hash_null);
    }

    // is_coinbase
    //
    {
      bool& v =
        o.is_coinbase;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.is_coinbase_value,
        i.is_coinbase_null);
    }

    // has_witness
    //
    {
      bool& v =
        o.has_witness;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.has_witness_value,
        i.has_witness_null);
    }

    // is_segwit_out_spend
    //
    {
      bool& v =
        o.is_segwit_out_spend;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.is_segwit_out_spend_value,
        i.is_segwit_out_spend_null);
    }

    // total_output_value
    //
    {
      ::int64_t& v =
        o.total_output_value;

      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_value (
        v,
        i.total_output_value_value,
        i.total_output_value_null);
    }

    // total_input_value
    //
    {
      ::int64_t& v =
        o.total_input_value;

      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_value (
        v,
        i.total_input_value_value,
        i.total_input_value_null);
    }

    // fees
    //
    {
      ::int64_t& v =
        o.fees;

      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_value (
        v,
        i.fees_value,
        i.fees_null);
    }

    // fee_per_byte
    //
    {
      float& v =
        o.fee_per_byte;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.fee_per_byte_value,
        i.fee_per_byte_null);
    }

    // fee_per_vbyte
    //
    {
      float& v =
        o.fee_per_vbyte;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.fee_per_vbyte_value,
        i.fee_per_vbyte_null);
    }

    // fee_per_weight_unit
    //
    {
      float& v =
        o.fee_per_weight_unit;

      pgsql::value_traits<
          float,
          pgsql::id_real >::set_value (
        v,
        i.fee_per_weight_unit_value,
        i.fee_per_weight_unit_null);
    }
  }

  void access::object_traits_impl< ::eTransactions, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::eTransactions, id_pgsql >::persist_statement[] =
  "INSERT INTO \"bitcoin\".\"eTransactions\" "
  "(\"id\", "
  "\"block_hash\", "
  "\"index\", "
  "\"size\", "
  "\"vsize\", "
  "\"weight\", "
  "\"inputs_count\", "
  "\"outputs_count\", "
  "\"lock_time\", "
  "\"version\", "
  "\"hash\", "
  "\"witness_hash\", "
  "\"is_coinbase\", "
  "\"has_witness\", "
  "\"is_segwit_out_spend\", "
  "\"total_output_value\", "
  "\"total_input_value\", "
  "\"fees\", "
  "\"fee_per_byte\", "
  "\"fee_per_vbyte\", "
  "\"fee_per_weight_unit\") "
  "VALUES "
  "(DEFAULT, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20) "
  "RETURNING \"id\"";

  const char access::object_traits_impl< ::eTransactions, id_pgsql >::find_statement[] =
  "SELECT "
  "\"bitcoin\".\"eTransactions\".\"id\", "
  "\"bitcoin\".\"eTransactions\".\"block_hash\", "
  "\"bitcoin\".\"eTransactions\".\"index\", "
  "\"bitcoin\".\"eTransactions\".\"size\", "
  "\"bitcoin\".\"eTransactions\".\"vsize\", "
  "\"bitcoin\".\"eTransactions\".\"weight\", "
  "\"bitcoin\".\"eTransactions\".\"inputs_count\", "
  "\"bitcoin\".\"eTransactions\".\"outputs_count\", "
  "\"bitcoin\".\"eTransactions\".\"lock_time\", "
  "\"bitcoin\".\"eTransactions\".\"version\", "
  "\"bitcoin\".\"eTransactions\".\"hash\", "
  "\"bitcoin\".\"eTransactions\".\"witness_hash\", "
  "\"bitcoin\".\"eTransactions\".\"is_coinbase\", "
  "\"bitcoin\".\"eTransactions\".\"has_witness\", "
  "\"bitcoin\".\"eTransactions\".\"is_segwit_out_spend\", "
  "\"bitcoin\".\"eTransactions\".\"total_output_value\", "
  "\"bitcoin\".\"eTransactions\".\"total_input_value\", "
  "\"bitcoin\".\"eTransactions\".\"fees\", "
  "\"bitcoin\".\"eTransactions\".\"fee_per_byte\", "
  "\"bitcoin\".\"eTransactions\".\"fee_per_vbyte\", "
  "\"bitcoin\".\"eTransactions\".\"fee_per_weight_unit\" "
  "FROM \"bitcoin\".\"eTransactions\" "
  "WHERE \"bitcoin\".\"eTransactions\".\"id\"=$1";

  const char access::object_traits_impl< ::eTransactions, id_pgsql >::update_statement[] =
  "UPDATE \"bitcoin\".\"eTransactions\" "
  "SET "
  "\"block_hash\"=$1, "
  "\"index\"=$2, "
  "\"size\"=$3, "
  "\"vsize\"=$4, "
  "\"weight\"=$5, "
  "\"inputs_count\"=$6, "
  "\"outputs_count\"=$7, "
  "\"lock_time\"=$8, "
  "\"version\"=$9, "
  "\"hash\"=$10, "
  "\"witness_hash\"=$11, "
  "\"is_coinbase\"=$12, "
  "\"has_witness\"=$13, "
  "\"is_segwit_out_spend\"=$14, "
  "\"total_output_value\"=$15, "
  "\"total_input_value\"=$16, "
  "\"fees\"=$17, "
  "\"fee_per_byte\"=$18, "
  "\"fee_per_vbyte\"=$19, "
  "\"fee_per_weight_unit\"=$20 "
  "WHERE \"id\"=$21";

  const char access::object_traits_impl< ::eTransactions, id_pgsql >::erase_statement[] =
  "DELETE FROM \"bitcoin\".\"eTransactions\" "
  "WHERE \"id\"=$1";

  const char access::object_traits_impl< ::eTransactions, id_pgsql >::query_statement[] =
  "SELECT "
  "\"bitcoin\".\"eTransactions\".\"id\", "
  "\"bitcoin\".\"eTransactions\".\"block_hash\", "
  "\"bitcoin\".\"eTransactions\".\"index\", "
  "\"bitcoin\".\"eTransactions\".\"size\", "
  "\"bitcoin\".\"eTransactions\".\"vsize\", "
  "\"bitcoin\".\"eTransactions\".\"weight\", "
  "\"bitcoin\".\"eTransactions\".\"inputs_count\", "
  "\"bitcoin\".\"eTransactions\".\"outputs_count\", "
  "\"bitcoin\".\"eTransactions\".\"lock_time\", "
  "\"bitcoin\".\"eTransactions\".\"version\", "
  "\"bitcoin\".\"eTransactions\".\"hash\", "
  "\"bitcoin\".\"eTransactions\".\"witness_hash\", "
  "\"bitcoin\".\"eTransactions\".\"is_coinbase\", "
  "\"bitcoin\".\"eTransactions\".\"has_witness\", "
  "\"bitcoin\".\"eTransactions\".\"is_segwit_out_spend\", "
  "\"bitcoin\".\"eTransactions\".\"total_output_value\", "
  "\"bitcoin\".\"eTransactions\".\"total_input_value\", "
  "\"bitcoin\".\"eTransactions\".\"fees\", "
  "\"bitcoin\".\"eTransactions\".\"fee_per_byte\", "
  "\"bitcoin\".\"eTransactions\".\"fee_per_vbyte\", "
  "\"bitcoin\".\"eTransactions\".\"fee_per_weight_unit\" "
  "FROM \"bitcoin\".\"eTransactions\"";

  const char access::object_traits_impl< ::eTransactions, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"bitcoin\".\"eTransactions\"";

  const char access::object_traits_impl< ::eTransactions, id_pgsql >::table_name[] =
  "\"bitcoin\".\"eTransactions\"";

  void access::object_traits_impl< ::eTransactions, id_pgsql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::eTransactions, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::eTransactions, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    ODB_POTENTIALLY_UNUSED (db);

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::eTransactions, id_pgsql >::pointer_type
  access::object_traits_impl< ::eTransactions, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::eTransactions, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::eTransactions, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::eTransactions, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::eTransactions, id_pgsql >::object_type >
  access::object_traits_impl< ::eTransactions, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::eTransactions, id_pgsql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
