/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "bitcoin"."eTransactions" CASCADE;

DROP TABLE IF EXISTS "schema_version";

CREATE TABLE "bitcoin"."eTransactions" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "block_hash" TEXT NOT NULL,
  "index" INTEGER NOT NULL,
  "size" INTEGER NOT NULL,
  "vsize" INTEGER NOT NULL,
  "weight" INTEGER NOT NULL,
  "inputs_count" INTEGER NOT NULL,
  "outputs_count" INTEGER NOT NULL,
  "lock_time" INTEGER NOT NULL,
  "version" INTEGER NOT NULL,
  "hash" TEXT NOT NULL,
  "witness_hash" TEXT NOT NULL,
  "is_coinbase" BOOLEAN NOT NULL,
  "has_witness" BOOLEAN NOT NULL,
  "is_segwit_out_spend" BOOLEAN NOT NULL,
  "total_output_value" BIGINT NOT NULL,
  "total_input_value" BIGINT NOT NULL,
  "fees" BIGINT NOT NULL,
  "fee_per_byte" REAL NOT NULL,
  "fee_per_vbyte" REAL NOT NULL,
  "fee_per_weight_unit" REAL NOT NULL);

CREATE TABLE "schema_version" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "version" BIGINT NOT NULL,
  "migration" BOOLEAN NOT NULL);

INSERT INTO "schema_version" (
  "name", "version", "migration")
  VALUES ('', 1, FALSE);

