// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "wallet/enterprise/models/support/output_entries-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // eOutputEntries
  //

  const char access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  persist_statement_name[] = "persist_eOutputEntries";

  const char access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  find_statement_name[] = "find_eOutputEntries";

  const char access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  update_statement_name[] = "update_eOutputEntries";

  const char access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  erase_statement_name[] = "erase_eOutputEntries";

  const char access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  query_statement_name[] = "query_eOutputEntries";

  const char access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  erase_query_statement_name[] = "erase_query_eOutputEntries";

  const unsigned int access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int2_oid,
    pgsql::int8_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::int4_oid
  };

  const unsigned int access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int4_oid
  };

  const unsigned int access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::int2_oid,
    pgsql::int8_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::int4_oid,
    pgsql::int4_oid
  };

  struct access::object_traits_impl< ::eOutputEntries, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::eOutputEntries, id_pgsql >::id_type
  access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  id (const id_image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::eOutputEntries, id_pgsql >::id_type
  access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id
    //
    t[0UL] = 0;

    // output_etransaction_id
    //
    t[1UL] = 0;

    // output_vector
    //
    t[2UL] = 0;

    // is_output_mine
    //
    t[3UL] = 0;

    // n_value
    //
    t[4UL] = 0;

    // destination
    //
    if (t[5UL])
    {
      i.destination_value.capacity (i.destination_size);
      grew = true;
    }

    // script_pub_key
    //
    if (t[6UL])
    {
      i.script_pub_key_value.capacity (i.script_pub_key_size);
      grew = true;
    }

    // input_etransaction_id
    //
    t[7UL] = 0;

    // input_vector
    //
    t[8UL] = 0;

    // script_sig
    //
    if (t[9UL])
    {
      i.script_sig_value.capacity (i.script_sig_size);
      grew = true;
    }

    // script_witness
    //
    if (t[10UL])
    {
      i.script_witness_value.capacity (i.script_witness_size);
      grew = true;
    }

    // n_sequence
    //
    t[11UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // id
    //
    if (sk != statement_insert && sk != statement_update)
    {
      b[n].type = pgsql::bind::integer;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // output_etransaction_id
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.output_etransaction_id_value;
    b[n].is_null = &i.output_etransaction_id_null;
    n++;

    // output_vector
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.output_vector_value;
    b[n].is_null = &i.output_vector_null;
    n++;

    // is_output_mine
    //
    b[n].type = pgsql::bind::smallint;
    b[n].buffer = &i.is_output_mine_value;
    b[n].is_null = &i.is_output_mine_null;
    n++;

    // n_value
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.n_value_value;
    b[n].is_null = &i.n_value_null;
    n++;

    // destination
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.destination_value.data ();
    b[n].capacity = i.destination_value.capacity ();
    b[n].size = &i.destination_size;
    b[n].is_null = &i.destination_null;
    n++;

    // script_pub_key
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.script_pub_key_value.data ();
    b[n].capacity = i.script_pub_key_value.capacity ();
    b[n].size = &i.script_pub_key_size;
    b[n].is_null = &i.script_pub_key_null;
    n++;

    // input_etransaction_id
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.input_etransaction_id_value;
    b[n].is_null = &i.input_etransaction_id_null;
    n++;

    // input_vector
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.input_vector_value;
    b[n].is_null = &i.input_vector_null;
    n++;

    // script_sig
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.script_sig_value.data ();
    b[n].capacity = i.script_sig_value.capacity ();
    b[n].size = &i.script_sig_size;
    b[n].is_null = &i.script_sig_null;
    n++;

    // script_witness
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.script_witness_value.data ();
    b[n].capacity = i.script_witness_value.capacity ();
    b[n].size = &i.script_witness_size;
    b[n].is_null = &i.script_witness_null;
    n++;

    // n_sequence
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.n_sequence_value;
    b[n].is_null = &i.n_sequence_null;
    n++;
  }

  void access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // output_etransaction_id
    //
    {
      unsigned int const& v =
        o.output_etransaction_id;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.output_etransaction_id_value, is_null, v);
      i.output_etransaction_id_null = is_null;
    }

    // output_vector
    //
    {
      unsigned int const& v =
        o.output_vector;

      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.output_vector_value, is_null, v);
      i.output_vector_null = is_null;
    }

    // is_output_mine
    //
    {
      ::uint8_t const& v =
        o.is_output_mine;

      bool is_null (false);
      pgsql::value_traits<
          ::uint8_t,
          pgsql::id_smallint >::set_image (
        i.is_output_mine_value, is_null, v);
      i.is_output_mine_null = is_null;
    }

    // n_value
    //
    {
      ::int64_t const& v =
        o.n_value;

      bool is_null (false);
      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_image (
        i.n_value_value, is_null, v);
      i.n_value_null = is_null;
    }

    // destination
    //
    {
      ::std::string const& v =
        o.destination;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.destination_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.destination_value,
        size,
        is_null,
        v);
      i.destination_null = is_null;
      i.destination_size = size;
      grew = grew || (cap != i.destination_value.capacity ());
    }

    // script_pub_key
    //
    {
      ::std::string const& v =
        o.script_pub_key;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.script_pub_key_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.script_pub_key_value,
        size,
        is_null,
        v);
      i.script_pub_key_null = is_null;
      i.script_pub_key_size = size;
      grew = grew || (cap != i.script_pub_key_value.capacity ());
    }

    // input_etransaction_id
    //
    {
      unsigned int const& v =
        o.input_etransaction_id;

      bool is_null (true);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.input_etransaction_id_value, is_null, v);
      i.input_etransaction_id_null = is_null;
    }

    // input_vector
    //
    {
      unsigned int const& v =
        o.input_vector;

      bool is_null (true);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.input_vector_value, is_null, v);
      i.input_vector_null = is_null;
    }

    // script_sig
    //
    {
      ::std::string const& v =
        o.script_sig;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.script_sig_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.script_sig_value,
        size,
        is_null,
        v);
      i.script_sig_null = is_null;
      i.script_sig_size = size;
      grew = grew || (cap != i.script_sig_value.capacity ());
    }

    // script_witness
    //
    {
      ::std::string const& v =
        o.script_witness;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.script_witness_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.script_witness_value,
        size,
        is_null,
        v);
      i.script_witness_null = is_null;
      i.script_witness_size = size;
      grew = grew || (cap != i.script_witness_value.capacity ());
    }

    // n_sequence
    //
    {
      ::uint32_t const& v =
        o.n_sequence;

      bool is_null (true);
      pgsql::value_traits<
          ::uint32_t,
          pgsql::id_integer >::set_image (
        i.n_sequence_value, is_null, v);
      i.n_sequence_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id
    //
    {
      unsigned int& v =
        o.id;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // output_etransaction_id
    //
    {
      unsigned int& v =
        o.output_etransaction_id;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i.output_etransaction_id_value,
        i.output_etransaction_id_null);
    }

    // output_vector
    //
    {
      unsigned int& v =
        o.output_vector;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i.output_vector_value,
        i.output_vector_null);
    }

    // is_output_mine
    //
    {
      ::uint8_t& v =
        o.is_output_mine;

      pgsql::value_traits<
          ::uint8_t,
          pgsql::id_smallint >::set_value (
        v,
        i.is_output_mine_value,
        i.is_output_mine_null);
    }

    // n_value
    //
    {
      ::int64_t& v =
        o.n_value;

      pgsql::value_traits<
          ::int64_t,
          pgsql::id_bigint >::set_value (
        v,
        i.n_value_value,
        i.n_value_null);
    }

    // destination
    //
    {
      ::std::string& v =
        o.destination;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.destination_value,
        i.destination_size,
        i.destination_null);
    }

    // script_pub_key
    //
    {
      ::std::string& v =
        o.script_pub_key;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.script_pub_key_value,
        i.script_pub_key_size,
        i.script_pub_key_null);
    }

    // input_etransaction_id
    //
    {
      unsigned int& v =
        o.input_etransaction_id;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i.input_etransaction_id_value,
        i.input_etransaction_id_null);
    }

    // input_vector
    //
    {
      unsigned int& v =
        o.input_vector;

      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_value (
        v,
        i.input_vector_value,
        i.input_vector_null);
    }

    // script_sig
    //
    {
      ::std::string& v =
        o.script_sig;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.script_sig_value,
        i.script_sig_size,
        i.script_sig_null);
    }

    // script_witness
    //
    {
      ::std::string& v =
        o.script_witness;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.script_witness_value,
        i.script_witness_size,
        i.script_witness_null);
    }

    // n_sequence
    //
    {
      ::uint32_t& v =
        o.n_sequence;

      pgsql::value_traits<
          ::uint32_t,
          pgsql::id_integer >::set_value (
        v,
        i.n_sequence_value,
        i.n_sequence_null);
    }
  }

  void access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      pgsql::value_traits<
          unsigned int,
          pgsql::id_integer >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::eOutputEntries, id_pgsql >::persist_statement[] =
  "INSERT INTO \"wallet\".\"eOutputEntries\" "
  "(\"id\", "
  "\"output_etransaction_id\", "
  "\"output_vector\", "
  "\"is_output_mine\", "
  "\"n_value\", "
  "\"destination\", "
  "\"script_pub_key\", "
  "\"input_etransaction_id\", "
  "\"input_vector\", "
  "\"script_sig\", "
  "\"script_witness\", "
  "\"n_sequence\") "
  "VALUES "
  "(DEFAULT, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) "
  "RETURNING \"id\"";

  const char access::object_traits_impl< ::eOutputEntries, id_pgsql >::find_statement[] =
  "SELECT "
  "\"wallet\".\"eOutputEntries\".\"id\", "
  "\"wallet\".\"eOutputEntries\".\"output_etransaction_id\", "
  "\"wallet\".\"eOutputEntries\".\"output_vector\", "
  "\"wallet\".\"eOutputEntries\".\"is_output_mine\", "
  "\"wallet\".\"eOutputEntries\".\"n_value\", "
  "\"wallet\".\"eOutputEntries\".\"destination\", "
  "\"wallet\".\"eOutputEntries\".\"script_pub_key\", "
  "\"wallet\".\"eOutputEntries\".\"input_etransaction_id\", "
  "\"wallet\".\"eOutputEntries\".\"input_vector\", "
  "\"wallet\".\"eOutputEntries\".\"script_sig\", "
  "\"wallet\".\"eOutputEntries\".\"script_witness\", "
  "\"wallet\".\"eOutputEntries\".\"n_sequence\" "
  "FROM \"wallet\".\"eOutputEntries\" "
  "WHERE \"wallet\".\"eOutputEntries\".\"id\"=$1";

  const char access::object_traits_impl< ::eOutputEntries, id_pgsql >::update_statement[] =
  "UPDATE \"wallet\".\"eOutputEntries\" "
  "SET "
  "\"output_etransaction_id\"=$1, "
  "\"output_vector\"=$2, "
  "\"is_output_mine\"=$3, "
  "\"n_value\"=$4, "
  "\"destination\"=$5, "
  "\"script_pub_key\"=$6, "
  "\"input_etransaction_id\"=$7, "
  "\"input_vector\"=$8, "
  "\"script_sig\"=$9, "
  "\"script_witness\"=$10, "
  "\"n_sequence\"=$11 "
  "WHERE \"id\"=$12";

  const char access::object_traits_impl< ::eOutputEntries, id_pgsql >::erase_statement[] =
  "DELETE FROM \"wallet\".\"eOutputEntries\" "
  "WHERE \"id\"=$1";

  const char access::object_traits_impl< ::eOutputEntries, id_pgsql >::query_statement[] =
  "SELECT "
  "\"wallet\".\"eOutputEntries\".\"id\", "
  "\"wallet\".\"eOutputEntries\".\"output_etransaction_id\", "
  "\"wallet\".\"eOutputEntries\".\"output_vector\", "
  "\"wallet\".\"eOutputEntries\".\"is_output_mine\", "
  "\"wallet\".\"eOutputEntries\".\"n_value\", "
  "\"wallet\".\"eOutputEntries\".\"destination\", "
  "\"wallet\".\"eOutputEntries\".\"script_pub_key\", "
  "\"wallet\".\"eOutputEntries\".\"input_etransaction_id\", "
  "\"wallet\".\"eOutputEntries\".\"input_vector\", "
  "\"wallet\".\"eOutputEntries\".\"script_sig\", "
  "\"wallet\".\"eOutputEntries\".\"script_witness\", "
  "\"wallet\".\"eOutputEntries\".\"n_sequence\" "
  "FROM \"wallet\".\"eOutputEntries\"";

  const char access::object_traits_impl< ::eOutputEntries, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"wallet\".\"eOutputEntries\"";

  const char access::object_traits_impl< ::eOutputEntries, id_pgsql >::table_name[] =
  "\"wallet\".\"eOutputEntries\"";

  void access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    ODB_POTENTIALLY_UNUSED (db);

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::eOutputEntries, id_pgsql >::pointer_type
  access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::eOutputEntries, id_pgsql >::object_type >
  access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::eOutputEntries, id_pgsql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
