// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef OUTPUT_ENTRIES_ODB_HXX
#define OUTPUT_ENTRIES_ODB_HXX

// Begin prologue.
//
#include <odb/boost/version.hxx>
#if ODB_BOOST_VERSION != 2040000 // 2.4.0
#  error ODB and C++ compilers see different libodb-boost interface versions
#endif
#include <odb/boost/uuid/pgsql/uuid-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "wallet/enterprise/models/output_entries.h"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // eOutputEntries
  //
  template <>
  struct class_traits< ::eOutputEntries >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::eOutputEntries >
  {
    public:
    typedef ::eOutputEntries object_type;
    typedef ::eOutputEntries* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // eOutputEntries
  //
  template <typename A>
  struct query_columns< ::eOutputEntries, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    id_type_;

    static const id_type_ id;

    // output_etransaction_id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    output_etransaction_id_type_;

    static const output_etransaction_id_type_ output_etransaction_id;

    // output_vector
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    output_vector_type_;

    static const output_vector_type_ output_vector;

    // is_output_mine
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint8_t,
        pgsql::id_smallint >::query_type,
      pgsql::id_smallint >
    is_output_mine_type_;

    static const is_output_mine_type_ is_output_mine;

    // n_value
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    n_value_type_;

    static const n_value_type_ n_value;

    // destination
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    destination_type_;

    static const destination_type_ destination;

    // script_pub_key
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    script_pub_key_type_;

    static const script_pub_key_type_ script_pub_key;

    // input_etransaction_id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    input_etransaction_id_type_;

    static const input_etransaction_id_type_ input_etransaction_id;

    // input_vector
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    input_vector_type_;

    static const input_vector_type_ input_vector;

    // script_sig
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    script_sig_type_;

    static const script_sig_type_ script_sig;

    // script_witness
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    script_witness_type_;

    static const script_witness_type_ script_witness;

    // n_sequence
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint32_t,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    n_sequence_type_;

    static const n_sequence_type_ n_sequence;
  };

  template <typename A>
  const typename query_columns< ::eOutputEntries, id_pgsql, A >::id_type_
  query_columns< ::eOutputEntries, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::eOutputEntries, id_pgsql, A >::output_etransaction_id_type_
  query_columns< ::eOutputEntries, id_pgsql, A >::
  output_etransaction_id (A::table_name, "\"output_etransaction_id\"", 0);

  template <typename A>
  const typename query_columns< ::eOutputEntries, id_pgsql, A >::output_vector_type_
  query_columns< ::eOutputEntries, id_pgsql, A >::
  output_vector (A::table_name, "\"output_vector\"", 0);

  template <typename A>
  const typename query_columns< ::eOutputEntries, id_pgsql, A >::is_output_mine_type_
  query_columns< ::eOutputEntries, id_pgsql, A >::
  is_output_mine (A::table_name, "\"is_output_mine\"", 0);

  template <typename A>
  const typename query_columns< ::eOutputEntries, id_pgsql, A >::n_value_type_
  query_columns< ::eOutputEntries, id_pgsql, A >::
  n_value (A::table_name, "\"n_value\"", 0);

  template <typename A>
  const typename query_columns< ::eOutputEntries, id_pgsql, A >::destination_type_
  query_columns< ::eOutputEntries, id_pgsql, A >::
  destination (A::table_name, "\"destination\"", 0);

  template <typename A>
  const typename query_columns< ::eOutputEntries, id_pgsql, A >::script_pub_key_type_
  query_columns< ::eOutputEntries, id_pgsql, A >::
  script_pub_key (A::table_name, "\"script_pub_key\"", 0);

  template <typename A>
  const typename query_columns< ::eOutputEntries, id_pgsql, A >::input_etransaction_id_type_
  query_columns< ::eOutputEntries, id_pgsql, A >::
  input_etransaction_id (A::table_name, "\"input_etransaction_id\"", 0);

  template <typename A>
  const typename query_columns< ::eOutputEntries, id_pgsql, A >::input_vector_type_
  query_columns< ::eOutputEntries, id_pgsql, A >::
  input_vector (A::table_name, "\"input_vector\"", 0);

  template <typename A>
  const typename query_columns< ::eOutputEntries, id_pgsql, A >::script_sig_type_
  query_columns< ::eOutputEntries, id_pgsql, A >::
  script_sig (A::table_name, "\"script_sig\"", 0);

  template <typename A>
  const typename query_columns< ::eOutputEntries, id_pgsql, A >::script_witness_type_
  query_columns< ::eOutputEntries, id_pgsql, A >::
  script_witness (A::table_name, "\"script_witness\"", 0);

  template <typename A>
  const typename query_columns< ::eOutputEntries, id_pgsql, A >::n_sequence_type_
  query_columns< ::eOutputEntries, id_pgsql, A >::
  n_sequence (A::table_name, "\"n_sequence\"", 0);

  template <typename A>
  struct pointer_query_columns< ::eOutputEntries, id_pgsql, A >:
    query_columns< ::eOutputEntries, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::eOutputEntries, id_pgsql >:
    public access::object_traits< ::eOutputEntries >
  {
    public:
    struct id_image_type
    {
      int id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      int id_value;
      bool id_null;

      // output_etransaction_id
      //
      int output_etransaction_id_value;
      bool output_etransaction_id_null;

      // output_vector
      //
      int output_vector_value;
      bool output_vector_null;

      // is_output_mine
      //
      short is_output_mine_value;
      bool is_output_mine_null;

      // n_value
      //
      long long n_value_value;
      bool n_value_null;

      // destination
      //
      details::buffer destination_value;
      std::size_t destination_size;
      bool destination_null;

      // script_pub_key
      //
      details::buffer script_pub_key_value;
      std::size_t script_pub_key_size;
      bool script_pub_key_null;

      // input_etransaction_id
      //
      int input_etransaction_id_value;
      bool input_etransaction_id_null;

      // input_vector
      //
      int input_vector_value;
      bool input_vector_null;

      // script_sig
      //
      details::buffer script_sig_value;
      std::size_t script_sig_size;
      bool script_sig_null;

      // script_witness
      //
      details::buffer script_witness_value;
      std::size_t script_witness_size;
      bool script_witness_null;

      // n_sequence
      //
      int n_sequence_value;
      bool n_sequence_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 12UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::eOutputEntries, id_common >:
    public access::object_traits_impl< ::eOutputEntries, id_pgsql >
  {
  };

  // eOutputEntries
  //
}

#include "wallet/enterprise/models/support/output_entries-odb.ixx"

#include <odb/post.hxx>

#endif // OUTPUT_ENTRIES_ODB_HXX
