/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "wallet"."eTransactions" CASCADE;

DROP TABLE IF EXISTS "schema_version";

CREATE TABLE "wallet"."eTransactions" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "block_id" INTEGER NOT NULL,
  "total_size" INTEGER NOT NULL,
  "inputs_count" INTEGER NOT NULL,
  "outputs_count" INTEGER NOT NULL,
  "value_out" BIGINT NOT NULL,
  "n_lock_time" INTEGER NOT NULL,
  "n_version" INTEGER NOT NULL,
  "hash" TEXT NOT NULL,
  "witness_hash" TEXT NOT NULL,
  "is_coinbase" BOOLEAN NOT NULL,
  "has_witness" BOOLEAN NOT NULL);

CREATE TABLE "schema_version" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "version" BIGINT NOT NULL,
  "migration" BOOLEAN NOT NULL);

INSERT INTO "schema_version" (
  "name", "version", "migration")
  VALUES ('', 1, FALSE);

