// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef TRANSACTIONS_ODB_HXX
#define TRANSACTIONS_ODB_HXX

// Begin prologue.
//
#include <odb/boost/version.hxx>
#if ODB_BOOST_VERSION != 2040000 // 2.4.0
#  error ODB and C++ compilers see different libodb-boost interface versions
#endif
#include <odb/boost/uuid/pgsql/uuid-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "wallet/enterprise/models/transactions.h"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // eTransactions
  //
  template <>
  struct class_traits< ::eTransactions >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::eTransactions >
  {
    public:
    typedef ::eTransactions object_type;
    typedef ::eTransactions* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // eTransactions
  //
  template <typename A>
  struct query_columns< ::eTransactions, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    id_type_;

    static const id_type_ id;

    // block_id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    block_id_type_;

    static const block_id_type_ block_id;

    // block_index
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    block_index_type_;

    static const block_index_type_ block_index;

    // is_trusted
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        bool,
        pgsql::id_boolean >::query_type,
      pgsql::id_boolean >
    is_trusted_type_;

    static const is_trusted_type_ is_trusted;

    // size
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    size_type_;

    static const size_type_ size;

    // time
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    time_type_;

    static const time_type_ time;

    // time_received
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    time_received_type_;

    static const time_received_type_ time_received;

    // txid
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    txid_type_;

    static const txid_type_ txid;

    // wallet_id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::uuids::uuid,
        pgsql::id_uuid >::query_type,
      pgsql::id_uuid >
    wallet_id_type_;

    static const wallet_id_type_ wallet_id;
  };

  template <typename A>
  const typename query_columns< ::eTransactions, id_pgsql, A >::id_type_
  query_columns< ::eTransactions, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::eTransactions, id_pgsql, A >::block_id_type_
  query_columns< ::eTransactions, id_pgsql, A >::
  block_id (A::table_name, "\"block_id\"", 0);

  template <typename A>
  const typename query_columns< ::eTransactions, id_pgsql, A >::block_index_type_
  query_columns< ::eTransactions, id_pgsql, A >::
  block_index (A::table_name, "\"block_index\"", 0);

  template <typename A>
  const typename query_columns< ::eTransactions, id_pgsql, A >::is_trusted_type_
  query_columns< ::eTransactions, id_pgsql, A >::
  is_trusted (A::table_name, "\"is_trusted\"", 0);

  template <typename A>
  const typename query_columns< ::eTransactions, id_pgsql, A >::size_type_
  query_columns< ::eTransactions, id_pgsql, A >::
  size (A::table_name, "\"size\"", 0);

  template <typename A>
  const typename query_columns< ::eTransactions, id_pgsql, A >::time_type_
  query_columns< ::eTransactions, id_pgsql, A >::
  time (A::table_name, "\"time\"", 0);

  template <typename A>
  const typename query_columns< ::eTransactions, id_pgsql, A >::time_received_type_
  query_columns< ::eTransactions, id_pgsql, A >::
  time_received (A::table_name, "\"time_received\"", 0);

  template <typename A>
  const typename query_columns< ::eTransactions, id_pgsql, A >::txid_type_
  query_columns< ::eTransactions, id_pgsql, A >::
  txid (A::table_name, "\"txid\"", 0);

  template <typename A>
  const typename query_columns< ::eTransactions, id_pgsql, A >::wallet_id_type_
  query_columns< ::eTransactions, id_pgsql, A >::
  wallet_id (A::table_name, "\"wallet_id\"", 0);

  template <typename A>
  struct pointer_query_columns< ::eTransactions, id_pgsql, A >:
    query_columns< ::eTransactions, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::eTransactions, id_pgsql >:
    public access::object_traits< ::eTransactions >
  {
    public:
    struct id_image_type
    {
      int id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      int id_value;
      bool id_null;

      // block_id
      //
      int block_id_value;
      bool block_id_null;

      // block_index
      //
      int block_index_value;
      bool block_index_null;

      // is_trusted
      //
      bool is_trusted_value;
      bool is_trusted_null;

      // size
      //
      int size_value;
      bool size_null;

      // time
      //
      long long time_value;
      bool time_null;

      // time_received
      //
      long long time_received_value;
      bool time_received_null;

      // txid
      //
      details::buffer txid_value;
      std::size_t txid_size;
      bool txid_null;

      // wallet_id
      //
      unsigned char wallet_id_value[16];
      bool wallet_id_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 9UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::eTransactions, id_common >:
    public access::object_traits_impl< ::eTransactions, id_pgsql >
  {
  };

  // eTransactions
  //
}

#include "wallet/enterprise/models/support/transactions-odb.ixx"

#include <odb/post.hxx>

#endif // TRANSACTIONS_ODB_HXX
