// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef WALLET_TRANSACTIONS_ODB_HXX
#define WALLET_TRANSACTIONS_ODB_HXX

// Begin prologue.
//
#include <odb/boost/version.hxx>
#if ODB_BOOST_VERSION != 2040000 // 2.4.0
#  error ODB and C++ compilers see different libodb-boost interface versions
#endif
#include <odb/boost/uuid/pgsql/uuid-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "wallet/enterprise/models/wallet_transactions.h"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // eWalletTransactions
  //
  template <>
  struct class_traits< ::eWalletTransactions >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::eWalletTransactions >
  {
    public:
    typedef ::eWalletTransactions object_type;
    typedef ::eWalletTransactions* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // eWalletTransactions
  //
  template <typename A>
  struct query_columns< ::eWalletTransactions, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    id_type_;

    static const id_type_ id;

    // etransaction_id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    etransaction_id_type_;

    static const etransaction_id_type_ etransaction_id;

    // is_trusted
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        bool,
        pgsql::id_boolean >::query_type,
      pgsql::id_boolean >
    is_trusted_type_;

    static const is_trusted_type_ is_trusted;

    // n_time_smart
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    n_time_smart_type_;

    static const n_time_smart_type_ n_time_smart;

    // n_time_received
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    n_time_received_type_;

    static const n_time_received_type_ n_time_received;

    // debit
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    debit_type_;

    static const debit_type_ debit;

    // credit
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::int64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    credit_type_;

    static const credit_type_ credit;

    // wallet_id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::uuids::uuid,
        pgsql::id_uuid >::query_type,
      pgsql::id_uuid >
    wallet_id_type_;

    static const wallet_id_type_ wallet_id;
  };

  template <typename A>
  const typename query_columns< ::eWalletTransactions, id_pgsql, A >::id_type_
  query_columns< ::eWalletTransactions, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::eWalletTransactions, id_pgsql, A >::etransaction_id_type_
  query_columns< ::eWalletTransactions, id_pgsql, A >::
  etransaction_id (A::table_name, "\"etransaction_id\"", 0);

  template <typename A>
  const typename query_columns< ::eWalletTransactions, id_pgsql, A >::is_trusted_type_
  query_columns< ::eWalletTransactions, id_pgsql, A >::
  is_trusted (A::table_name, "\"is_trusted\"", 0);

  template <typename A>
  const typename query_columns< ::eWalletTransactions, id_pgsql, A >::n_time_smart_type_
  query_columns< ::eWalletTransactions, id_pgsql, A >::
  n_time_smart (A::table_name, "\"n_time_smart\"", 0);

  template <typename A>
  const typename query_columns< ::eWalletTransactions, id_pgsql, A >::n_time_received_type_
  query_columns< ::eWalletTransactions, id_pgsql, A >::
  n_time_received (A::table_name, "\"n_time_received\"", 0);

  template <typename A>
  const typename query_columns< ::eWalletTransactions, id_pgsql, A >::debit_type_
  query_columns< ::eWalletTransactions, id_pgsql, A >::
  debit (A::table_name, "\"debit\"", 0);

  template <typename A>
  const typename query_columns< ::eWalletTransactions, id_pgsql, A >::credit_type_
  query_columns< ::eWalletTransactions, id_pgsql, A >::
  credit (A::table_name, "\"credit\"", 0);

  template <typename A>
  const typename query_columns< ::eWalletTransactions, id_pgsql, A >::wallet_id_type_
  query_columns< ::eWalletTransactions, id_pgsql, A >::
  wallet_id (A::table_name, "\"wallet_id\"", 0);

  template <typename A>
  struct pointer_query_columns< ::eWalletTransactions, id_pgsql, A >:
    query_columns< ::eWalletTransactions, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::eWalletTransactions, id_pgsql >:
    public access::object_traits< ::eWalletTransactions >
  {
    public:
    struct id_image_type
    {
      int id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      int id_value;
      bool id_null;

      // etransaction_id
      //
      int etransaction_id_value;
      bool etransaction_id_null;

      // is_trusted
      //
      bool is_trusted_value;
      bool is_trusted_null;

      // n_time_smart
      //
      long long n_time_smart_value;
      bool n_time_smart_null;

      // n_time_received
      //
      long long n_time_received_value;
      bool n_time_received_null;

      // debit
      //
      long long debit_value;
      bool debit_null;

      // credit
      //
      long long credit_value;
      bool credit_null;

      // wallet_id
      //
      unsigned char wallet_id_value[16];
      bool wallet_id_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 8UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::eWalletTransactions, id_common >:
    public access::object_traits_impl< ::eWalletTransactions, id_pgsql >
  {
  };

  // eWalletTransactions
  //
}

#include "wallet/enterprise/models/support/wallet_transactions-odb.ixx"

#include <odb/post.hxx>

#endif // WALLET_TRANSACTIONS_ODB_HXX
