/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "wallet"."eWalletTransactions" CASCADE;

DROP TABLE IF EXISTS "schema_version";

CREATE TABLE "wallet"."eWalletTransactions" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "etransaction_id" INTEGER NOT NULL,
  "is_trusted" BOOLEAN NOT NULL,
  "n_time_smart" BIGINT NOT NULL,
  "n_time_received" BIGINT NOT NULL,
  "debit" BIGINT NOT NULL,
  "credit" BIGINT NOT NULL,
  "wallet_id" UUID NOT NULL);

CREATE TABLE "schema_version" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "version" BIGINT NOT NULL,
  "migration" BOOLEAN NOT NULL);

INSERT INTO "schema_version" (
  "name", "version", "migration")
  VALUES ('', 1, FALSE);

