/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "etransactions" CASCADE;

DROP TABLE IF EXISTS "schema_version";

CREATE TABLE "etransactions" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "txid" TEXT NOT NULL,
  "time" INTEGER NOT NULL);

CREATE UNIQUE INDEX "etransactions_txid_i"
  ON "etransactions" ("txid");

CREATE TABLE "schema_version" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "version" BIGINT NOT NULL,
  "migration" BOOLEAN NOT NULL);

INSERT INTO "schema_version" (
  "name", "version", "migration")
  VALUES ('', 1, FALSE);

